# Based on code by AndySymons https://community.home-assistant.io/t/how-best-to-interface-ring-camera-motion-sensors-to-alarmo/826730/1

blueprint:
  name: Dahua event to input boolean
  description: Detects a dahua motion event and turns on a boolean helper for 5 seconds, then off again
  domain: automation
  author: Steve
  input:
    camera_name:
      name: Camera entity
      description: Camera name (dahua) 
      selector:
        device:
          filter:
            - integration: dahua
          entity:
            - domain: camera
    motion_event:
      name: Event
      description: Event type
      selector:
        select:
          options:
            - SmartMotionHuman
            - CrossRegionDetection
            - VideoMotion
    region_name:
      name: Region Name
      description: Region (data.data.Name)
      selector:
        text:
    helper_input_boolean:
      name: Motion helper
      description: Input boolean helper to be operated by this automation
      selector:
        entity:
          filter:
            domain: input_boolean
          multiple: false 

mode: restart
max_exceeded: silent

alias: Dahua motion event for !camera_name !motion_event !region_name

triggers:
  - event_type: dahua_event_received
    event_data:
      Code: !motion_event
      action: Start
    trigger: event
conditions: []

actions:
  - action: input_boolean.turn_on
    target:
      entity_id: !input helper_input_boolean
    data: {}

  - delay:
      hours: 0
      minutes: 0
      seconds: 5

  - action: input_boolean.turn_off
    target:
      entity_id: !input helper_input_boolean
    data: {}

  - delay:
      hours: 0
      minutes: 0
      seconds: 5
